### ISSUE TITLE
ROS2 Support

### ISSUE THREAD

**Issue by gulerburak** [SICKAG/sick_visionary_ros#1]
## Summary

Is this package supports ROS 2? If not, will be there a support for ROS 2?

**Comment by zimmefaSICKAG** [comment]
This is ROS1 only. ROS2 is not supported.

**Comment by a-parkkonen-navi** [comment]
Hi! Does the Safevisionary ROS2 driver work with Visionary-T Mini?

**Comment by xfealal** [comment]
Hello a-parkkonen-navi,
the Visionary-T Mini is not supported by the Safevisionary ROS2 driver.
However, a dedicated ROS2 driver for the Visionary-T Mini is in planning.

**Comment by a-parkkonen-navi** [comment]
Is this an official answer from SICK? @zimmefaSICKAG @peichtoSICKAG

**Comment by zimmefaSICKAG** [comment]
Yes, this is an official SICK answer from xfealal.

**Comment by jabbenseth** [comment]
> Hello a-parkkonen-navi, the Visionary-T Mini is not supported by the Safevisionary ROS2 driver. However, a dedicated ROS2 driver for the Visionary-T Mini is in planning.

any updates on what "in planning" means today?

**Comment by a-parkkonen-navi** [comment]
I'm also still interested on this.

**Comment by xfealal** [comment]
Hello @jabbenseth, @a-parkkonen-navi, 
the release of the ROS2 driver for the Visionary-T Mini is to be expected in early 2025. 
Best regards.

**Comment by pschnattinger** [comment]
Hey is there any update to this?

**Comment by zimmefaSICKAG** [comment]
We are finalizing the development of the ROS2 driver just now. Our current estimate is that it will be available by the beginning of March. In a first step, it will be made available via [sick.com](sick.com). The publication via github will follow in a second, later step.
Please note: The ROS2 driver will require a Visionary-T Mini AP (V3S145-1xx) and a GigEVision streaming app that will be made available via the [SICK AppPool](https://apppool.cloud.sick.com/).

**Comment by zimmefaSICKAG** [comment]
We are happy to finally announce the release of the **ROS2 driver** for our Visionary cameras. You can find it [here](https://github.com/SICKAG/sick_visionary_gev_ros2).

**Comment by a-parkkonen-navi** [comment]
Thanks for the update! Great to hear!

**Comment by jabbenseth** [comment]
Great news. Thanks very much
