### ISSUE TITLE
Can I set t mni cx's exposure?

### ISSUE THREAD

**Issue by Navifra-Dan** [SICKAG/sick_visionary_ros#5]
I am currently using this repository for my project, but I am experiencing difficulties due to noise caused by excessive light. I would like to know if there are any filtering methods to reduce this light-induced noise or if there is a way to adjust the exposure settings on the T-Mini CX device itself.

![IMG_4709](https://github.com/user-attachments/assets/38db0811-bdcc-4271-88b3-61ea29be54e2)

**Comment by zimmefaSICKAG** [comment]
Dear Navifra-Dan,

thanks for working with our Visionary-T Mini camera. Great to see you managed to integrate it into your ROS environment.
We are eager to support you. However, please note the following regarding support (copied from the top-level README):

Depending on the nature of your question, there are two support channels:

For questions regarding the code shared in this repo please check the FAQ first and [search if an issue already exists](https://github.com/SICKAG/sick_visionary_ros/issues). If a related issue doesn't exist, you can open a new issue using the [issue form](https://github.com/SICKAG/sick_visionary_ros/issues/new/choose).
**For application or device specific questions** look for common solutions and knowledge articles on the [Sick Support Portal](https://support.sick.com/). If your question is not answered there, open a ticket on the [Sick Support Portal](https://support.sick.com/).

So in your case, please open a ticket on the SICK Support Portal.
